//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_APPLICATION.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_ADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ADMIN()
        {
            this.TBL_CATEGORY = new HashSet<TBL_CATEGORY>();
        }
    
        public int AD_ID { get; set; }

        [Required(ErrorMessage ="Please Enter Username")]
        [Display(Name="Teacher Username")]
        public string AD_NAME { get; set; }

        [Required(ErrorMessage = "Please Enter Password")]
        [Display(Name = "Teacher Password")]
        public string AD_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CATEGORY> TBL_CATEGORY { get; set; }
    }
}
