//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_APPLICATION.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_QUESTION
    {
        public int QUESTION_ID { get; set; }

        
        [Display(Name = "Question: ")]
        public string Q_TEXT { get; set; }

        [Display(Name = "A : ")]
        public string OPA { get; set; }

        [Display(Name = "B : ")]
        public string OPB { get; set; }

        [Display(Name = "C : ")]
        public string OPC { get; set; }

        [Display(Name = "D : ")]
        public string OPD { get; set; }


        public string COP { get; set; }
        [Display(Name = "Select Question You Want Create")]
        public Nullable<int> Q_FK_CATID { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
    }
}
