//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZ_APPLICATION.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STUDENT()
        {
            this.TBL_SETEXAM = new HashSet<TBL_SETEXAM>();
        }
    
        public int STD_ID { get; set; }

        [Required(ErrorMessage = "Please Enter Username")]
        [Display(Name = "Student Username")]
        public string STD_NAME { get; set; }

        [Required(ErrorMessage = "Please Enter Username")]
        [Display(Name = "Student Password")]
        public string STD_PASSWORD { get; set; }

        public string STD_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SETEXAM> TBL_SETEXAM { get; set; }
    }
}
